<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
<ul><li>
')->setMessageSeparatorString('</li><li>')->setMessageCloseString('</li></ul></div>');
echo $flash->render('error',    array('alert', 'alert-dismissable', 'alert-danger'));
echo $flash->render('info',     array('alert', 'alert-dismissable', 'alert-info'));
echo $flash->render('default',  array('alert', 'alert-dismissable', 'alert-default'));
echo $flash->render('success',  array('alert', 'alert-dismissable', 'alert-success'));
?>
<table class="table table-striped table-hover">
    <tbody><tr>
        <th>Имя</th>
        <th>Дата</th>
        <th>Текст</th>

    </tr>
    <?php
    foreach ($result as $item ) {
        echo "<tr>
                <td>{$item->getName()}</td>
                <td>{$item->getDate()}</td>
                <td>{$item->getText()}</td>
                ";
        }
    ?>
    </tbody>
</table>

<?php

$form->setAttribute('action', $this->url('user/guest', array('action' => 'index')));
$form->prepare();

echo $this->form()->openTag($form);
echo '<legend>Ваш отзыв</legend>';
foreach($form as $element)
{
    $attributes = $element->getAttributes();

    if($element->getLabel())
    {
        $element->setLabelAttributes(array('class' => 'control-label'));
        if(isset($attributes['required']))
        {
            $element->setLabel($element->getLabel(). ' *');
        }

    }
    if(isset($attributes['type']) && $attributes['type'] == 'text')
    {
        echo $this->formLabel($element)."<br>";
        echo $this->formInput($element)."<br>";
    }
    else
    {
        echo $this->formRow($element)."<br>";
    }

}
echo $this->form()->closeTag();
?>