<h1>Категории</h1>
<div class="admin">
<a href="/admin/category/add/">Добавить категорию</a><br><br><br>

<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
<ul><li>
')->setMessageSeparatorString('</li><li>')->setMessageCloseString('</li></ul></div>');

echo $flash->render('error',    array('alert', 'alert-dismissable', 'alert-danger'));
echo $flash->render('info',     array('alert', 'alert-dismissable', 'alert-info'));
echo $flash->render('default',  array('alert', 'alert-dismissable', 'alert-default'));
echo $flash->render('success',  array('alert', 'alert-dismissable', 'alert-success'));
?>
<table class="table table-striped table-hover">
    <tbody>
    <tr>
        <th>#</th>
        <th>Название категории</th>
        <th>Действие</th>
    </tr>
    <?php
    foreach ($category as $item ) {
        echo "<tr>
                <td> {$item->getId()}</td>
                <td>{$item->getCategory()}</td>";
    echo '
    <td><a href="'.$this->url('admin/category', array('action' => 'edit', 'id' => $item->getId())).'">Редактировать</a>&nbsp;&nbsp
        <a href="'.$this->url('admin/category', array('action' => 'delete', 'id' => $item->getId())).'" onclick="if (confirm(\'Удалить запись?\')){document.location = this.href;} return false;">Удалить</a></td>
</tr>';
    }

    ?>
    </tbody>
</table>
</div>