<h1>Книги</h1>
<div class="admin">
<a href="/admin/books/add/">Добавить</a>
<?php
    $flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
<ul><li>
')->setMessageSeparatorString('</li><li>')->setMessageCloseString('</li></ul></div>');
echo $flash->render('error',    array('alert', 'alert-dismissable', 'alert-danger'));
echo $flash->render('info',     array('alert', 'alert-dismissable', 'alert-info'));
echo $flash->render('default',  array('alert', 'alert-dismissable', 'alert-default'));
echo $flash->render('success',  array('alert', 'alert-dismissable', 'alert-success'));
?>
<table class="table table-striped table-hover">
    <tbody><tr>
        <th>isbn</th>
        <th>Автор</th>
        <th>Название</th>
        <th>Категория</th>
        <th>Аннотация</th>
        <th>Страниц:</th>
        <th>Цена</th>
        <th>Картинка</th>
        <th>Действие</th>
        </tr>
    <?php
foreach ($books as $item ) {
    $category = $item->getCategory();
    if ($category) {
        $catName = $category->getCategory();
    }

    echo "<tr>
<td>{$item->getIsbn()}</td>
<td>{$item->getAuthor()}</td>
<td>{$item->getTitle()}</td>
<td>{$catName}</td>
<td>{$item->getAnotationForTable()}</td>
<td>{$item->getPages()}</td>
<td>{$item->getPrice()}</td>
<td><img src='{$item->getPicturename()}' height='200' width='150' alt='dd0'> </td>
";
    echo '
    <td><a href="' . $this->url(
            'admin/books', array('action' => 'edit', 'id' => $item->getIsbn())
        ) . '">Редактировать</a>&nbsp;&nbsp
        <a href="' . $this->url(
            'admin/books',
            array('action' => 'delete', 'id' => $item->getIsbn())
        ) . '" onclick="if (confirm(\'Удалить Книгу?\')){document.location = this.href;} return false;">Удалить</a></td>
</tr>';

}
    ?>
    </tbody>
</table>
</div>
<?php
echo $this->paginationControl($books,'Sliding', 'pagination_control', array('route'=>'admin/books'));
