<h1>Заказы</h1>


<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
<ul><li>
')->setMessageSeparatorString('</li><li>')->setMessageCloseString('</li></ul></div>');

echo $flash->render('error',    array('alert', 'alert-dismissable', 'alert-danger'));
echo $flash->render('info',     array('alert', 'alert-dismissable', 'alert-info'));
echo $flash->render('default',  array('alert', 'alert-dismissable', 'alert-default'));
echo $flash->render('success',  array('alert', 'alert-dismissable', 'alert-success'));
?>
<table class="table table-striped table-hover">
    <tbody>
    <tr>
        <th>#</th>
        <th>isbn</th>
        <th>Имя</th>
        <th>Фамилия</th>
        <th>Номер телефона</th>
        <th>Действие</th>
    </tr>
    <?php
    foreach ($zakaz as $item ) {
        echo "<tr>
                <td> {$item->getId()}</td>
                <td>{$item->getIsbn()}</td>
                <td>{$item->getName()}</td>
                 <td>{$item->getSecondName()}</td>
                  <td>{$item->getNumber()}</td>
                ";
        echo '
    <td>
        <a style="text-decoration: none; color:black;" href="'.$this->url('admin/books', array('action' => 'delete', 'id' => $item->getId())).'" onclick="if (confirm(\'Удалить запись?\')){document.location = this.href;} return false;">Обработано</a></td>
</tr>';
    }

    ?>
    </tbody>
</table>
<br><br><br><br><br><br><br><br>