<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<script>
    function check() {
        var text = $("#check_email").val();
        var myData = {textData:text};
        $.ajax({
            type: "POST",
            dataType: "Json",
            url: "/user/register/group/",

            data: myData,
            success: function (data) {
                if (data.name != false) {
                    $("#answers").text("Такой E-mail уже существует");
                }
                else {
                    $("#answers").text("Этот E-mail свободен ");
                }
            }
        });
    }
</script>
<?php

$form->setAttribute('action', $this->url('user/register', array('action' => 'process')));
$form->prepare();

echo $this->form()->openTag($form);
echo '<fieldset><legend>Регистрация</legend>';
foreach($form as $element)
{
    $attributes = $element->getAttributes();

    if($element->getLabel())
    {
        $element->setLabelAttributes(array('class' => 'control-label'));
        if(isset($attributes['required']))
        {
            $element->setLabel($element->getLabel(). ' *');
        }

    }

    if(isset($attributes['type']) && $attributes['type'] == 'text')
    {
        echo $this->formLabel($element)."<br>";
        echo $this->formInput($element)."<br>";
    }
    elseif((isset($attributes['type']) && $attributes['type'] == 'email')) {
        echo $this->formLabel($element)."<br>";
        echo $this->formEmail($element);
        echo ' <span id="answers" class="answer"></span><br>';
    }
    elseif((isset($attributes['type']) && $attributes['type'] == 'password')) {
        echo $this->formLabel($element)."<br>";
        echo $this->formPassword($element)."<br>";
    }
    elseif((isset($attributes['type']) && $attributes['type'] == 'date')) {
        echo $this->formLabel($element)."<br>";
        echo $this->formDate($element)."<br>";
    }
    else
    {
        echo $this->formRow($element)."<br>";
    }

}
echo '</fieldset>';
echo $this->form()->closeTag();
?>